
export enum ValidationErrorCode {
    // === Course Metadata ===
    COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
    COURSE_DELETED = 'COURSE_DELETED',
    MISSING_TITLE = 'MISSING_TITLE',
    MISSING_SLUG = 'MISSING_SLUG',
    MISSING_THUMBNAIL = 'MISSING_THUMBNAIL',
    MISSING_INTRODUCTION = 'MISSING_INTRODUCTION',
    MISSING_LEARNING_OUTCOMES = 'MISSING_LEARNING_OUTCOMES',
    MISSING_REQUIREMENTS = 'MISSING_REQUIREMENTS',
    MISSING_COURSE_TYPE = 'MISSING_COURSE_TYPE',
    MISSING_LEVEL = 'MISSING_LEVEL',
    INVALID_INSTRUCTOR = 'INVALID_INSTRUCTOR',
    CATEGORY_INACTIVE = 'CATEGORY_INACTIVE',

    // === Pricing ===
    FREE_COURSE_HAS_PRICE = 'FREE_COURSE_HAS_PRICE',
    PAID_COURSE_NO_PRICE = 'PAID_COURSE_NO_PRICE',
    DISCOUNT_EXCEEDS_PRICE = 'DISCOUNT_EXCEEDS_PRICE',

    // === Curriculum ===
    MIN_SECTION_COUNT = 'MIN_SECTION_COUNT',
    MIN_LESSON_COUNT = 'MIN_LESSON_COUNT',
    SECTION_EMPTY = 'SECTION_EMPTY',
    LESSON_MISSING_TITLE = 'LESSON_MISSING_TITLE',
    LESSON_MISSING_CONTENT = 'LESSON_MISSING_CONTENT',

    // === Video ===
    VIDEO_PENDING = 'VIDEO_PENDING',
    VIDEO_UPLOADING = 'VIDEO_UPLOADING',
    VIDEO_PROCESSING = 'VIDEO_PROCESSING',
    VIDEO_FAILED = 'VIDEO_FAILED',
    VIDEO_NOT_READY = 'VIDEO_NOT_READY',
    VIDEO_DURATION_TOO_SHORT = 'VIDEO_DURATION_TOO_SHORT',
    YOUTUBE_VIDEO_NOT_FOUND = 'YOUTUBE_VIDEO_NOT_FOUND',

    // === R2 Storage ===
    RESOURCE_NOT_FOUND_R2 = 'RESOURCE_NOT_FOUND_R2',

    // === Cloudinary ===
    THUMBNAIL_NOT_FOUND = 'THUMBNAIL_NOT_FOUND',
    LESSON_IMAGE_NOT_FOUND = 'LESSON_IMAGE_NOT_FOUND',

    // === External ===
    EXTERNAL_CHECK_FAILED = 'EXTERNAL_CHECK_FAILED',
}

/** Số section tối thiểu */
export const MIN_SECTIONS = 1;

/** Số lesson tối thiểu */
export const MIN_LESSONS = 5;

/** Tổng thời lượng video tối thiểu (giây) — 30 phút */
export const MIN_VIDEO_DURATION_SECONDS = 30 * 60; // 1800s

/** Batch size cho YouTube API (tối đa 50 ids/request) */
export const YOUTUBE_BATCH_SIZE = 50;

/** Số lượng R2 HeadObject request đồng thời */
export const R2_CONCURRENCY = 10;
